server.port: ${SERVER_PORT:8080}

spring:
  grpc:
    client:
      channel:
        backend-service:
          target: static://${BACKEND_HOST:localhost}:${BACKEND_PORT:9091}

logging:
  level:
    com.example.vsd.frontend: debug