server.port: 7759

spring:
  sql.init.mode: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service-desk
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
#    defer-datasource-initialization: true

hibernate:
  default-schema: public
  show-sql: true
  format-sql: true
  enable-lazy-load-no-trans: true

logging.level:
  root: info
  org.atmosphere: warn

