syntax = "proto3";

package sd.messages;

import "google/protobuf/timestamp.proto";
import "google/type/date.proto";

option java_multiple_files = true;
option java_package = "com.example.vsd.grpc.messages";

message OrderProto {
  optional int64 id = 1;
  optional string name = 2;
  optional string description = 3;
  optional google.type.Date start_line = 4;
  optional google.type.Date dead_line = 5;
  optional google.type.Date first_control_line = 6;
  optional google.type.Date second_control_line = 7;
  optional int32 days_count = 8;
  optional google.protobuf.Timestamp completed_date = 9;
  optional OrderStatusProto status = 10;
  optional ClientProto client = 11;
  optional AgentProto agent = 12;
  optional string service_desk_number = 13;
  optional google.protobuf.Timestamp creation_date = 14;
  optional google.protobuf.Timestamp last_updated = 15;
  optional bool deleted = 16;
}

enum OrderStatusProto {
  NEW = 0;
  IN_PROGRESS = 1;
  FIRST_CONTROL = 2;
  SECOND_CONTROL = 3;
  COMPLETED = 4;
}

message AgentProto {
  optional int64 id = 1;
  optional string name = 2;
  optional string service_desk_number = 3;
  optional google.protobuf.Timestamp creation_date = 4;
  optional google.protobuf.Timestamp lastUpdated = 5;
  optional bool deleted = 6;
}

message ClientProto {
  optional int64 id = 1;
  optional string name = 2;
  optional string service_desk_number = 3;
  optional google.protobuf.Timestamp creation_date = 4;
  optional google.protobuf.Timestamp lastUpdated = 5;
  optional bool deleted = 6;
}

message BaseEntityProto {
  oneof payload {
    ClientProto client = 1;
    AgentProto agent = 2;
    OrderProto order = 3;
  }
}

message GetClientsResponse {
  repeated ClientProto clients = 1;
}

message GetAgentsResponse {
  repeated AgentProto agents = 1;
}

message GetOrdersResponse {
  repeated OrderProto orders = 1;
}

message GetRecycleResponse {
  repeated BaseEntityProto recycles = 1;
}