CREATE TABLE IF NOT EXISTS public.agents (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    service_desk_number varchar(20) GENERATED ALWAYS AS ('AG-' || lpad(id::text, 3, '0')) STORED,
    agent_name varchar(50) NOT NULL,
    creation_date timestamp(3) without time zone NOT NULL,
    last_updated timestamp(3) without time zone NOT NULL,
    deleted boolean NOT NULL,
    CONSTRAINT pk_agents PRIMARY KEY (id),
    CONSTRAINT uk_agents_name UNIQUE (agent_name)
);

CREATE TABLE IF NOT EXISTS public.clients (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    service_desk_number varchar(20) GENERATED ALWAYS AS ('CL-' || lpad(id::text, 5, '0')) STORED,
    client_name varchar(70) NOT NULL,
    creation_date timestamp(3) without time zone NOT NULL,
    last_updated timestamp(3) without time zone NOT NULL,
    deleted boolean NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT uk_clients_name UNIQUE (client_name)
);

CREATE TABLE IF NOT EXISTS public.orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    service_desk_number varchar(20) GENERATED ALWAYS AS ('SD-' || lpad(id::text, 8, '0')) STORED,
    title varchar(50) NOT NULL,
    description varchar(200),
    start_line date NOT NULL,
    dead_line date NOT NULL,
    completed_date timestamp(3) without time zone,
    agent_id bigint NOT NULL,
    client_id bigint NOT NULL,
    creation_date timestamp(3) without time zone NOT NULL,
    last_updated timestamp(3) without time zone NOT NULL,
    deleted boolean NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fk_orders_client_id FOREIGN KEY (client_id)
        REFERENCES public.clients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_orders_agent_id FOREIGN KEY (agent_id)
        REFERENCES public.agents (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.mail_data (
    id bigint NOT NULL,
    app_mail varchar(255),
    app_mail_host varchar(255),
    app_mail_password varchar(255),
    app_mail_port varchar(255),
    target_mail varchar(255),
    mail_smtp_auth boolean NOT NULL,
    mail_smtp_start_tls boolean NOT NULL,
    CONSTRAINT pk_mail_data PRIMARY KEY (id)
);