syntax = "proto3";

package sd.services;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "messages/manager_messages.proto";

option java_multiple_files = true;
option java_package = "com.example.vsd.grpc.services.admin";
option java_outer_classname = "AdminAgentControllerProto";

service AdminAgentController {
  rpc saveAgent (sd.messages.AgentProto) returns (google.protobuf.Empty);
  rpc setAgentDeleted (google.protobuf.Int64Value) returns (google.protobuf.Empty);
  rpc restoreAgent (google.protobuf.Int64Value) returns (google.protobuf.Empty);
  rpc deleteAgentPermanently (google.protobuf.Int64Value) returns (google.protobuf.Empty);
}